### PR TITLE
postgis, django db connection pool

### PR DESCRIPTION
**Pull request by buckmaxwell**

### CODE REVIEW

**Comment by altairbow** [comment]
Have you tested this backend?
I think you only need [dj_db_conn_pool/backends/postgis/__init__.py](https://github.com/altairbow/django-db-connection-pool/pull/41/files#diff-9a57d0f76067df354da654a4cf7ef866c7bd267d88aea0bea5f674286ced23f6) and [dj_db_conn_pool/backends/postgis/base.py](https://github.com/altairbow/django-db-connection-pool/pull/41/files#diff-46017719bcdda9872fb3d4e74930002e51683e9286887a43ab40597d028b2918)
and you may need define `SQLAlchemyDialect` in dj_db_conn_pool/backends/postgis/base.DatabaseWrapper for postgis

**Comment by buckmaxwell** [comment]
altair - I am using it and it seems to work, but I am not sure if the actual connection pooling works. What do you think is the best way to tell?

**Comment by altairbow** [comment]
> @altairbow - I am using it and it seems to work, but I am not sure if the actual connection pooling works. What do you think is the best way to tell?

OK, try  [this branch](https://github.com/altairbow/django-db-connection-pool/tree/postgis), I deleted dj_db_conn_pool/backends/postgis/django_tenants/*

**Comment by hadpro24** [comment]
Hi @altairbow this branch is not avalaible

**Pull request closed without merging**
